version: "3"
services:
  web:
    container_name: commerce-api
    restart: always
    build: .
    ports:
      - "3001:3000"
    links:
      - database
    volumes:
      - .:/app # named volume
      - /app/node_modules # anonymous volume for node_modules only
  database:
    container_name: mongodatabase
    image: mongo
    ports: 
      - "27018:27017"
    logging:
      driver: none